//! One row of the session list, framework-neutral.
//!
//! The list is a projection of the saved sessions plus the built-in local shells,
//! and every frontend wants the same projection: the same grouping, the same search
//! matching, the same "which row carries the group header" bookkeeping. That logic
//! used to produce a type generated by the UI toolkit, so none of it could be reused
//! by a second frontend — the same problem the terminal's span type had, and solved
//! the same way.
//!
//! Strings here rather than `SharedString`/`ModelRc`, and plain `bool`/`i32` rather
//! than whatever a toolkit's property type is, so this type can be built, compared
//! and tested without a toolkit in scope. The one frontend left converts at its own
//! boundary, in `crate::ui`.

/// One session-list row.
///
/// A row exists for group headers and empty-folder placeholders too, not only for
/// sessions: the list renders as a flat sequence with headings, and a frontend that
/// had to synthesise its own headings would disagree with this one about ordering.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SessionRow {
    /// The saved session's id, or empty for a placeholder row.
    ///
    /// Empty means "this row is a group with nothing in it" — there is no session to
    /// open, edit or delete behind it, and the list uses that to gate those actions
    /// rather than checking the group state separately.
    pub(crate) id: String,
    pub(crate) name: String,
    pub(crate) host: String,
    /// Device, baud rate and framing for a serial session; empty for every other
    /// kind. Shown in place of `user@host:port`, which a serial port has none of.
    pub(crate) serial_detail: String,
    pub(crate) port: i32,
    pub(crate) user: String,
    /// How this session authenticates, as the wire spelling.
    pub(crate) auth: String,
    /// ISO timestamp of the last connection, or `"never"`.
    pub(crate) last_used: String,
    /// The folder this row belongs to. Empty means ungrouped, which the list renders
    /// as the `"default"` group.
    pub(crate) group: String,
    /// Set on the first row of each group and empty on the rest, so a frontend draws
    /// one heading per group without having to track the previous row's group.
    pub(crate) group_header: String,
    /// Whether this row's group is collapsed.
    pub(crate) collapsed: bool,
    /// A built-in local shell rather than a saved server. Built-ins cannot be
    /// edited, reordered or deleted.
    pub(crate) builtin: bool,
}
